config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "accounts#show"

  #
  # WELCOME 
  #
  get '/sign-in', to: "welcome#signin", as: :signin
  post '/sign-in', to: "welcome#signin_do", as: :do_signin
  get '/sign-up', to: "welcome#signup", as: :signup
  post '/sign-up', to: "welcome#signup_do", as: :do_signup
  get '/signout', to: "welcome#signout", as: :signout

  #
  # ACCOUNTS 
  #
  get '/accounts', to: "accounts#select_accounts", as: :select_accounts
  get '/accounts/create/step-1', to: "accounts#create_account_1", as: :create_account_1
  post '/accounts/create/step-1', to: "accounts#create_account_1_do", as: :do_create_account_1
  get '/accounts/create/step-2', to: "accounts#create_account_2", as: :create_account_2
  post '/accounts/create/step-2', to: "accounts#create_account_2_do", as: :do_create_account_2
  get '/accounts/:id/select-plan', to: "accounts#select_plan", as: :select_plan
  get '/accounts/:account_token/select-plan/:plan_apikey', to: "accounts#select_plan_do", as: :do_select_plan
  get '/accounts/:id', to: "accounts#select_accounts_do", as: :do_select_accounts
  
  #
  # USERS
  #
  get '/users/invites/:invite_apikey/accept', to: 'users#accept_invite', as: :accept_invite
  get '/users/invites/:invite_apikey/decline', to: 'users#decline_invite', as: :decline_invite
  get '/users/invites', to: 'users#invites', as: :invites
  get '/users/invites/remove/:invite_apikey', to: 'users#remove_invite', as: :remove_invite
  get '/users/invites/resend/:invite_apikey', to: 'users#resend_invite', as: :resend_invite
  get '/users/new', to: 'users#new', as: :new_user
  post '/users/new', to: 'users#new_do', as: :do_new_user
  get '/users/:user_apikey/edit', to: 'users#edit', as: :edit_user
  get '/users', to: 'users#index', as: :users
  get '/users/:user_apikey', to: 'users#show', as: :show_user

  #
  # PROJECTS 
  #
  get '/projects', to: "projects#index", as: :projects
  get '/projects/new', to: "projects#new", as: :new_project
  post '/projects/create', to: "projects#create", as: :do_create_project
  get '/projects/:project_apikey', to: "projects#show", as: :show_project

  #
  # FORMS
  #
  get '/projects/:project_apikey/new', to: "custom_forms#new", as: :new_form
  post '/projects/:project_apikey/new', to: "custom_forms#create", as: :create_form
  get '/projects/:project_apikey/:form_apikey', to: "custom_forms#show", as: :show_form
  
  # FORM FIELDS
  get '/projects/:project_apikey/:form_apikey/new-form-field', to: "custom_forms#new_form_field", as: :new_form_field
  post '/projects/:project_apikey/:form_apikey/new-form-field', to: "custom_forms#create_form_field", as: :create_form_field
  get  '/projects/:project_apikey/:form_apikey/:form_field_apikey/edit', to: "custom_forms#edit_form_field", as: :edit_form_field
  post '/projects/:project_apikey/:form_apikey/:form_field_apikey/edit', to: "custom_forms#update_form_field", as: :update_form_field
  get  '/projects/:project_apikey/:form_apikey/:form_field_apikey/destroy', to: "custom_forms#destroy_form_field", as: :destroy_form_field

  # FORM SUBMISSIONS
  get '/projects/:project_apikey/:form_apikey/submission/:form_submission_apikey', to: "custom_forms#show_form_submission", as: :show_form_submission

  namespace :api do
    namespace :v1 do # Optional: API versioning
      get '/hello-world', to: 'custom_forms#hello_world'
      post '/form-submission/:form_apikey', to: 'custom_forms#form_submission'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    layout 'auth'

    def signin
    end

    def signin_do
        user = User.authenticate(params[:email], params[:password])
        if user
            session[:current_user] = user
            session[:user_id] = user.apikey
            session[:expiry_time] = Time.current.to_s
            # if user == "FAILED" #Catch for 2FA fail
            #     page = error_path
            # else
            #     #page = dashboard_path
            #     page = account_selection_path
            # end
            redirect_to select_accounts_path
        else
            flash[:error] = "Your email or password was incorrect."
            redirect_to signin_path
        end
    end

    def signup
    end

    def signup_do
        user = User.new(first_name: params[:first_name],
                        last_name: params[:last_name],
                        email: params[:email],
                        password: params[:password],
                        password_confirmation: params[:password_confirmation])

        if user.save
            session[:current_user] = user
            session[:user_id] = user.apikey
            session[:expiry_time] = Time.current.to_s
            #update the user
            #send the welcome email
            #ProfileMailer.with(user: user, base_url: Figaro.env.base_url).welcome.deliver_now
            redirect_to select_accounts_path
        else
            p user.errors.full_messages
            flash[:notice] = "Oops. #{user.errors.full_messages}"
            redirect_to signup_path
        end
    end

    def signout
        reset_session
        flash[:notice] = "You are signed out"
        redirect_to signin_path
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/signin.html.erb
<!--begin::Form-->
<div class="d-flex flex-center flex-column flex-lg-row-fluid">
    <!--begin::Wrapper-->
    <div class="w-lg-500px p-10">
        <!--begin::Form-->
        <!--<form class="form w-100" novalidate="novalidate" id="kt_sign_in_form" data-kt-redirect-url="index.html" action="#">-->
        <%= form_tag(do_signin_path, novalidate: 'novalidate', class: "form w-100") do %>
            <!--begin::Heading-->
            <div class="text-center mb-11">
                <!--begin::Title-->
                <h1 class="text-gray-900 fw-bolder mb-3">Sign In</h1>
                <!--end::Title-->
                <!--begin::Subtitle-->
                <div class="text-gray-500 fw-semibold fs-6">Your Social Campaigns</div>
                <!--end::Subtitle=-->
            </div>
            <!--begin::Heading-->
            <!--begin::Login options-->
            <div class="row g-3 mb-9">
                <!--begin::Col-->
                <div class="col-md-6">
                    <!--begin::Google link=-->
                    <a href="#" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                    <%= image_tag 'svg/google-icon.svg', class: "h-15px me-3", alt: "Logo" %>
                    Sign in with Google</a>
                    <!--end::Google link=-->
                </div>
                <!--end::Col-->
                <!--begin::Col-->
                <div class="col-md-6">
                    <!--begin::Google link=-->
                    <a href="#" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                    <%= image_tag 'svg/apple-black.svg', class: "theme-light-show h-15px me-3", alt: "Logo" %>
                    <%= image_tag 'svg/apple-black-dark.svg', class: "theme-dark-show h-15px me-3", alt: "Logo" %>
                    Sign in with Apple</a>
                    <!--end::Google link=-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Login options-->
            <!--begin::Separator-->
            <div class="separator separator-content my-14">
                <span class="w-125px text-gray-500 fw-semibold fs-7">Or with email</span>
            </div>
            <!--end::Separator-->
            <!--begin::Input group=-->
            <div class="fv-row mb-8">
                <!--begin::Email-->
                <input type="text" placeholder="Email" name="email" autocomplete="off" autofocus class="form-control bg-transparent" />
                <!--end::Email-->
            </div>
            <!--end::Input group=-->
            <div class="fv-row mb-3">
                <!--begin::Password-->
                <input type="password" placeholder="Password" name="password" autocomplete="off" class="form-control bg-transparent" />
                <!--end::Password-->
            </div>
            <!--end::Input group=-->
            <!--begin::Wrapper-->
            <div class="d-flex flex-stack flex-wrap gap-3 fs-base fw-semibold mb-8">
                <div></div>
                <!--begin::Link-->
                <a href="authentication/layouts/corporate/reset-password.html" class="link-primary">Forgot Password ?</a>
                <!--end::Link-->
            </div>
            <!--end::Wrapper-->
            <!--begin::Submit button-->
            <div class="d-grid mb-10">
                <button type="submit" id="kt_sign_in_submit" class="btn btn-primary">
                    <!--begin::Indicator label-->
                    <span class="indicator-label">Sign In</span>
                    <!--end::Indicator label-->
                    <!--begin::Indicator progress-->
                    <span class="indicator-progress">Please wait... 
                    <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                    <!--end::Indicator progress-->
                </button>
            </div>
            <!--end::Submit button-->
            <!--begin::Sign up-->
            <div class="text-gray-500 text-center fw-semibold fs-6">Not a Member yet? 
                <a href="<%= signup_path %>" class="link-primary">Sign up</a>
            </div>
            <!--end::Sign up-->
        <!--</form>-->
        <% end %>
        <!--end::Form-->
    </div>
    <!--end::Wrapper-->
</div>
<!--end::Form-->

app/views/welcome/signup.html.erb
<!--begin::Form-->
<div class="d-flex flex-center flex-column flex-lg-row-fluid">
    <!--begin::Wrapper-->
    <div class="w-lg-500px p-10">
        <!--begin::Form-->
        <%= form_tag(do_signup_path, novalidate: 'novalidate', class: "form w-100") do %>
            <!--begin::Heading-->
            <div class="text-center mb-11">
                <!--begin::Title-->
                <h1 class="text-gray-900 fw-bolder mb-3">Sign Up</h1>
                <!--end::Title-->
                <!--begin::Subtitle-->
                <div class="text-gray-500 fw-semibold fs-6">Your Social Campaigns</div>
                <!--end::Subtitle=-->
            </div>
            <!--begin::Heading-->
            <!--begin::Login options-->
            <div class="row g-3 mb-9">
                <!--begin::Col-->
                <div class="col-md-6">
                    <!--begin::Google link=-->
                    <a href="#" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                    <%= image_tag 'svg/google-icon.svg', class: "h-15px me-3", alt: "Logo" %>
                    Sign in with Google</a>
                    <!--end::Google link=-->
                </div>
                <!--end::Col-->
                <!--begin::Col-->
                <div class="col-md-6">
                    <!--begin::Google link=-->
                    <a href="#" class="btn btn-flex btn-outline btn-text-gray-700 btn-active-color-primary bg-state-light flex-center text-nowrap w-100">
                    <%= image_tag 'svg/apple-black.svg', class: "theme-light-show h-15px me-3", alt: "Logo" %>
                    <%= image_tag 'svg/apple-black-dark.svg', class: "theme-dark-show h-15px me-3", alt: "Logo" %>
                    Sign in with Apple</a>
                    <!--end::Google link=-->
                </div>
                <!--end::Col-->
            </div>
            <!--end::Login options-->
            <!--begin::Separator-->
            <div class="separator separator-content my-14">
                <span class="w-125px text-gray-500 fw-semibold fs-7">Or with email</span>
            </div>
            <!--end::Separator-->
            <!--begin::Input group=-->
            <div class="fv-row mb-8 row">
                <!--begin::First Name-->
                <div class="col-md-6 mb-8 mb-md-0">
                    <input type="text" placeholder="First Name" id="first_name" name="first_name" autocomplete="off" class="form-control bg-transparent" />
                </div>
                <!--end::First Name-->
                <!--begin::Last Name-->
                <div class="col-md-6">
                    <input type="text" placeholder="Last Name" id="last_name" name="last_name" autocomplete="off" class="form-control bg-transparent" />
                </div>
                <!--end::Last Name-->
            </div>
            <!--begin::Input group-->
            <!--begin::Input group=-->
            <div class="fv-row mb-8">
                <!--begin::Email-->
                <input type="text" placeholder="Email" id="email" name="email" autocomplete="off" class="form-control bg-transparent" />
                <!--end::Email-->
            </div>
            <!--begin::Input group-->
            <div class="fv-row mb-8" data-kt-password-meter="true">
                <!--begin::Wrapper-->
                <div class="mb-1">
                    <!--begin::Input wrapper-->
                    <div class="position-relative mb-3">
                        <input class="form-control bg-transparent" type="password" placeholder="Password" id="password" name="password" autocomplete="off" />
                        <span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2" data-kt-password-meter-control="visibility">
                            <i class="ki-duotone ki-eye-slash fs-2"></i>
                            <i class="ki-duotone ki-eye fs-2 d-none"></i>
                        </span>
                    </div>
                    <!--end::Input wrapper-->
                    <!--begin::Meter-->
                    <div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
                        <div class="flex-grow-1 bg-secondary bg-active-danger rounded h-5px me-2"></div>
                        <div class="flex-grow-1 bg-secondary bg-active-warning rounded h-5px me-2"></div>
                        <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
                        <div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
                    </div>
                    <!--end::Meter-->
                </div>
                <!--end::Wrapper-->
                <!--begin::Hint-->
                <div class="text-muted">Use 8 or more characters with a mix of letters, numbers & symbols.</div>
                <!--end::Hint-->
            </div>
            <!--end::Input group=-->
            <!--end::Input group=-->
            <div class="fv-row mb-8">
                <!--begin::Confirm Password-->
                <input placeholder="Confirm Password" id="password_confirmation" name="password_confirmation" type="password" autocomplete="off" class="form-control bg-transparent" />
                <!--end::Confirm Password-->
            </div>
            <!--end::Input group=-->
            <!--begin::Accept-->
            <div class="fv-row mb-8">
                <label class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="toc" value="1" />
                    <span class="form-check-label fw-semibold text-gray-700 fs-base ms-1">I Accept the 
                    <a href="#" class="ms-1 link-primary">Terms</a></span>
                </label>
            </div>
            <!--end::Accept-->
            <!--begin::Submit button-->
            <div class="d-grid mb-10">
                <button type="submit" id="kt_sign_up_submit" class="btn btn-primary">
                    <!--begin::Indicator label-->
                    <span class="indicator-label">Sign up</span>
                    <!--end::Indicator label-->
                    <!--begin::Indicator progress-->
                    <span class="indicator-progress">Please wait... 
                    <span class="spinner-border spinner-border-sm align-middle ms-2"></span></span>
                    <!--end::Indicator progress-->
                </button>
            </div>
            <!--end::Submit button-->
            <!--begin::Sign up-->
            <div class="text-gray-500 text-center fw-semibold fs-6">Already have an Account? 
            <a href="authentication/layouts/corporate/sign-in.html" class="link-primary fw-semibold">Sign in</a></div>
            <!--end::Sign up-->
        <% end %>
        <!--end::Form-->
    </div>
    <!--end::Wrapper-->
</div>
<!--end::Form-->