config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "accounts#show"

  #
  # WELCOME 
  #
  get '/sign-in', to: "welcome#signin", as: :signin
  post '/sign-in', to: "welcome#signin_do", as: :do_signin
  get '/sign-up', to: "welcome#signup", as: :signup
  post '/sign-up', to: "welcome#signup_do", as: :do_signup
  get '/signout', to: "welcome#signout", as: :signout

  #
  # ACCOUNTS 
  #
  get '/accounts', to: "accounts#select_accounts", as: :select_accounts
  get '/accounts/create/step-1', to: "accounts#create_account_1", as: :create_account_1
  post '/accounts/create/step-1', to: "accounts#create_account_1_do", as: :do_create_account_1
  get '/accounts/create/step-2', to: "accounts#create_account_2", as: :create_account_2
  post '/accounts/create/step-2', to: "accounts#create_account_2_do", as: :do_create_account_2
  get '/accounts/:id/select-plan', to: "accounts#select_plan", as: :select_plan
  get '/accounts/:account_token/select-plan/:plan_apikey', to: "accounts#select_plan_do", as: :do_select_plan
  get '/accounts/:id', to: "accounts#select_accounts_do", as: :do_select_accounts
  
  #
  # USERS
  #
  get '/users/invites/:invite_apikey/accept', to: 'users#accept_invite', as: :accept_invite
  get '/users/invites/:invite_apikey/decline', to: 'users#decline_invite', as: :decline_invite
  get '/users/invites', to: 'users#invites', as: :invites
  get '/users/invites/remove/:invite_apikey', to: 'users#remove_invite', as: :remove_invite
  get '/users/invites/resend/:invite_apikey', to: 'users#resend_invite', as: :resend_invite
  get '/users/new', to: 'users#new', as: :new_user
  post '/users/new', to: 'users#new_do', as: :do_new_user
  get '/users/:user_apikey/edit', to: 'users#edit', as: :edit_user
  get '/users', to: 'users#index', as: :users
  get '/users/:user_apikey', to: 'users#show', as: :show_user

  #
  # PROJECTS 
  #
  get '/projects', to: "projects#index", as: :projects
  get '/projects/new', to: "projects#new", as: :new_project
  post '/projects/create', to: "projects#create", as: :do_create_project
  get '/projects/:project_apikey', to: "projects#show", as: :show_project

  #
  # FORMS
  #
  get '/projects/:project_apikey/new', to: "custom_forms#new", as: :new_form
  post '/projects/:project_apikey/new', to: "custom_forms#create", as: :create_form
  get '/projects/:project_apikey/:form_apikey', to: "custom_forms#show", as: :show_form
  
  # FORM FIELDS
  get '/projects/:project_apikey/:form_apikey/new-form-field', to: "custom_forms#new_form_field", as: :new_form_field
  post '/projects/:project_apikey/:form_apikey/new-form-field', to: "custom_forms#create_form_field", as: :create_form_field
  get  '/projects/:project_apikey/:form_apikey/:form_field_apikey/edit', to: "custom_forms#edit_form_field", as: :edit_form_field
  post '/projects/:project_apikey/:form_apikey/:form_field_apikey/edit', to: "custom_forms#update_form_field", as: :update_form_field
  get  '/projects/:project_apikey/:form_apikey/:form_field_apikey/destroy', to: "custom_forms#destroy_form_field", as: :destroy_form_field

  # FORM SUBMISSIONS
  get '/projects/:project_apikey/:form_apikey/submission/:form_submission_apikey', to: "custom_forms#show_form_submission", as: :show_form_submission

  namespace :api do
    namespace :v1 do # Optional: API versioning
      get '/hello-world', to: 'custom_forms#hello_world'
      post '/form-submission/:form_apikey', to: 'custom_forms#form_submission'
    end
  end
end

app/controllers/api/v1/custom_forms_controller.rb
class Api::V1::CustomFormsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:form_submission]

    def hello_world
        render json: {message: "Hello World"}
    end

    def form_submission
        p "*" * 50
        p "PARAMS"
        p params
        p "*" * 50
        form = CustomForm.find_by_apikey(params[:form_apikey])
        if form && params[:response]
            data = []
            params[:response].each do |response|
                data << [ response[0], response[1].to_s ]
            end

            form_submission = FormSubmission.new(:raw_data => data, :custom_form_id => form.id)
            if form_submission.save
                render json: { message: "Submission saved."}
            else
                render json: { error: "Submission could not be saved."}
            end
        end
    end
end

app/controllers/custom_forms_controller.rb
class CustomFormsController < ApplicationController
    before_action :authenticate_user
    before_action :user_accounts
    before_action :set_account
    before_action :set_breadcrumbs
    layout 'dashboard'

    #
    # Custom Forms
    #
    def index
        project = Project.find_by_apikey(params[:project_apikey])
        @forms = project.forms
    end

    def show
        @form = CustomForm.find_by_apikey(params[:form_apikey])
        @form_fields = FormField.for_form(@form.id).order(order_num: :asc)
        add_breadcrumb(@form.name)

    end

    def new
        @form = CustomForm.new()
    end

    def create
        project = Project.find_by_apikey(params[:project_apikey])
        if project
            form = CustomForm.new(name: params[:form_name], description: params[:form_description], project_id: project.id)
            if form.save
                flash[:success] = "Form saved."
                redirect_to show_form_path(project.apikey, form.apikey)
            else
                p "*" * 50
                p "ERROR"
                p "*" * 50
                flash[:error] = "Couldn't save form. #{form.errors.full_messages}"
            end
        else
            p "*" * 50
            p "ERROR"
            p "*" * 50
            flash[:error] = "Couldn't find project."
        end
    end

    def edit
        @form = CustomForm.find_by_apikey(params[:form_apikey])
    end

    def update
        form = CustomForm.find_by_apikey(params[:form_apikey])
        form.name = params[:form_name]

        if form && form.save
            flash[:success] = "Form updated."
            redirect_to admin_custom_forms_path
        else
            p "*" * 50
            p "ERROR"
            p "*" * 50
            flash[:error] = "Couldn't save form. #{form.errors.full_messages}"
        end
    end

    #
    # Form Fields
    #
    def new_form_field
        @form = CustomForm.find_by_apikey(params[:form_apikey])
        @form_field = FormField.new()
    end

    def create_form_field
        project = Project.find_by_apikey(params[:project_apikey])
        form = CustomForm.find_by_apikey(params[:form_apikey])
        if form && project
            form_field = FormField.new(form_field_params.merge(:custom_form_id => form.id))

            if form_field.save
                field_children = params[:form_children]
                if field_children
                field_children.each do |child|
                    field_child = FormFieldChild.create(:name => child[1], :form_field_id => form_field.id)
                    p field_child
                end
                end

                flash[:success] = "Form field saved."
                redirect_to show_form_path(project.apikey, form.apikey) + "#form-builder"
            else
                p "*" * 50
                p "ERROR"
                p "*" * 50
                flash[:error] = "Couldn't save form field. #{form_field.errors.full_messages}"
            end
        else
            flash[:error] = "Couldn't find form. #{form.errors.full_messages}"
        end
    end

    def edit_form_field
        @form = CustomForm.find_by_apikey(params[:form_apikey])
        @field = FormField.find_by_apikey(params[:form_field_apikey])
        add_breadcrumb(@form.name, show_form_path(params[:project_apikey], @form.apikey))
        add_breadcrumb('Edit form field')
    end

    def update_form_field
        project = Project.find_by_apikey(params[:project_apikey])
        form = CustomForm.find_by_apikey(params[:form_apikey])
        form_field = FormField.find_by_apikey(params[:form_field_apikey])
        if form_field && form && project
            if form_field.update(form_field_params.merge(:custom_form_id => form.id))
                field_children = params[:form_children]
                if field_children
                    field_children.each do |child|
                        field_child = FormFieldChild.create(:name => child[1], :form_field_id => form_field.id)
                        p field_child
                    end
                end

                flash[:success] = "Form field saved."
                redirect_to show_form_path(project.apikey, form.apikey) + "#form-builder"
            else
                p "*" * 50
                p "ERROR"
                p "*" * 50
                flash[:error] = "Couldn't save form field. #{form_field.errors.full_messages}"
            end
        else
            flash[:error] = "Couldn't find form. #{form.errors.full_messages}"
        end
    end
    
    def destroy_form_field
        project = Project.find_by_apikey(params[:project_apikey])
        form = CustomForm.find_by_apikey(params[:form_apikey])
        field = FormField.find_by_apikey(params[:form_field_apikey])
        if field.destroy
            flash[:success] = "Form field deleted."
            redirect_to show_form_path(project.apikey, form.apikey) + "#form-builder"
        end
    end

    def reorder_form_fields
        items = parse_md_array(params[:items_order])

        # Update curriculum with new order
        items.each do |f|
        form_field = FormField.find_by_apikey(f[0])
        if (form_field && form_field.order_num != f[1])
            form_field.update(:order_num => f[1])
        end
        end

        # Refresh page to update preview - not ideal, but the javascript gets messy quickly here.. maybe later.
        redirect_to admin_show_custom_form_path(params[:form_apikey])
    end

    #
    # Form Submissions
    #
    def show_form_submission
        @submission = FormSubmission.find_by_apikey(params[:form_submission_apikey])

        @data = @submission.data
    end

    private

    def set_breadcrumbs
        add_breadcrumb(@current_account.name, root_path)
        project = Project.find_by_apikey(params[:project_apikey])
        add_breadcrumb(project.name, show_project_path(project.apikey))
    end

    def form_field_params
        params.permit(:name, :field_type, :col_width, :required, :placeholder, :label_as_placeholder)
    end

    # Parse string to multi-dimentional array
    def parse_md_array(string)
        items = string.gsub(/\[\[|\]\]/, '').split(/\], \[/)
        new_items = []
        items.each do |item|
        new_items << item.split(", ")
        end

        return new_items
    end
end

app/helpers/api/v1/custom_forms_helper.rb
module Api::V1::CustomFormsHelper
end

app/helpers/custom_forms_helper.rb
module CustomFormsHelper
    def form_html(form)
        html = "<form action='http://localhost:3000/api/v1/form-submission/#{form.apikey}' method='post'>"
        form.form_fields.each do |field|
            html += form_field(field)
            html += "<input type='hidden' id='response[#{field.field_id}][field_type]' name='response[#{field.field_id}][field_type]' value='#{field.field_type}' />"
            html += "<input type='hidden' id='response[#{field.field_id}][name]' name='response[#{field.field_id}][name]' value='#{field.name}' />"
        end
        html += "<button type='submit'>Submit</button>"
        html += "\n</form>"
        return html
    end

    # CONTROLLER
    def form_field(field)
        field_type = FormField::TYPES[field.field_type]
        case field_type[:element].downcase
        when "input"
            if !field_type[:has_children]
                input_field(field)
            else
                input_children_field(field)
            end
        when "select"
            select_field(field)
        when "textarea"
            textarea_field(field)
        end
    end

    # FIELDS
    def input_field(field)
        "
        #{field_label(field)}
        <input class='form-control' #{'required' if field.required} id='#{response_id(field.field_id)}[value]' name='#{response_id(field.field_id)}[value]' type='#{ field.field_type }' placeholder='#{field.label_as_placeholder ? field.name : field.placeholder}' />
        ".html_safe
    end

    def input_children_field(field)
        children = ''
        case field.field_type
        when "radio"
            children =  collection_radio_buttons('response[' + field.field_id + ']', 'value', field.form_field_children.all, :name, :name, {}, required: field.required) do |b|
                "<div>
                #{ b.label { b.radio_button(style: "margin-right: .5rem") + b.text } }
                </div>".html_safe
            end
        when "checkbox"
            # TODO: Make it so not all checkboxes have to be required
            children = collection_check_boxes('response[' + field.field_id + ']', 'value', field.form_field_children.all, :name, :name, { :include_hidden => false }, required: field.required ) do |b|
                "<div>
                #{ b.label { b.check_box(style: "margin-right: .5rem") + b.text } }
                </div>".html_safe
            end
        end
            "
            #{field_label(field)}
            <div class='col'>
            #{children}
            </div>
            ".html_safe
    end

    def select_field(field)
        options = ''
        field.form_field_children.each do |child|
            options += "<option value='#{child.name}'>#{child.name}</option>"
        end

        "
        #{field_label(field)}
        <select class='form-control' #{'required' if field.required} id='#{response_id(field.field_id)}[value]' name='#{response_id(field.field_id)}[value]'>
        #{options}
        </select>
        ".html_safe
    end

    def textarea_field(field)
        "
        #{field_label(field)}
        <textarea class='form-control' #{'required' if field.required} id='#{response_id(field.field_id)}[value]' name='#{response_id(field.field_id)}[value]' type='#{ field.field_type }' >#{field.label_as_placeholder ? field.name : field.placeholder}</textarea>
        ".html_safe
    end

    # CONSTANTS
    def field_label(field)
        field.label_as_placeholder ? '' :
        "<label for='#{response_id(field.field_id)}[value]' >#{ field.name }#{'<span class="text-danger"> *</span>' if field.required }</label>".html_safe
    end

    def response_id(field_id)
        "response[#{ field_id }]"
    end
end

app/views/custom_forms/show_tabs/_form_builder.html.erb
<!--begin::Summary-->
<div class="card card-flush h-lg-100">
    <!--begin::Card header-->
    <div class="card-header mt-6">
        <!--begin::Card title-->
        <div class="card-title flex-column">
            <h3 class="fw-bold mb-1">Form Builder</h3>
            <div class="fs-6 fw-semibold text-gray-500">24 Overdue Tasks</div>
        </div>
        <!--end::Card title-->
        <!--begin::Card toolbar-->
        <div class="card-toolbar">
            <button type="button" class="btn btn-sm btn-light me-3" data-bs-toggle="modal" data-bs-target="#embedModal">Embed</button>
            <button type="button" class="btn btn-sm btn-light-primary" data-bs-toggle="modal" data-bs-target="#newFormFieldModal">New Form Field</button>
        </div>
        <!--end::Card toolbar-->
    </div>
    <!--end::Card header-->
    <!--begin::Card body-->
    <div class="card-body p-9 pt-5">
        <div class="row" id="form-fields-preview">
            <% @form.form_fields.each do |field| %>
                <div class="mb-3 col-12 col-md-<%= field.col_width %> form-field">
                    <div class="form-field__edit-overlay btn-group">
                        <a href="<%= edit_form_field_path(params[:project_apikey], @form.apikey, field.apikey) %>" class="edit-overlay__btn btn btn-sm btn-light-primary">Edit</a>
                        <button class="edit-overlay__btn btn btn-sm btn-light-primary" data-overlay-action="move">Move</button>
                        <button class="edit-overlay__btn btn btn-sm btn-light-danger" data-overlay-action="destroy" data-field="<%= field.to_json(:only => [:apikey, :name]) %>">Destroy</button>
                    </div>
                    <%= form_field(field) %>
                    <input type="hidden" id="response[<%= field.field_id %>][field_type]" name="response[<%= field.field_id %>][field_type]" value="<%= field.field_type %>" />
                    <input type="hidden" id="response[<%= field.field_id %>][name]" name="response[<%= field.field_id %>][name]" value="<%= field.name %>" />
                </div>
            <% end %>
        </div>
        <button class="btn btn-primary">Submit</button>
    </div>
    <!--end::Card body-->
</div>
<!--end::Summary-->

<!-- begin::New Form Field Modal -->
<div class="modal fade" id="newFormFieldModal" tabindex="-1" aria-labelledby="newFormFieldModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="newFormFieldModalLabel">Form Field</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <%= form_with url: create_form_field_path(params[:project_apikey], @form.apikey), id: "new-form-field-form" do |f| %>
                <%= render 'custom_forms/show_tabs/form_field_form', f: f %>
            <% end %>
        </div>
    </div>
</div>
<!-- end::New Form Field Modal -->
<!-- begin::Embed Modal -->
<div class="modal fade" id="embedModal" tabindex="-1" aria-labelledby="embedModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="embedModalLabel">Embed</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            <pre><code><%= form_html(@form) %></code></pre>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light-secondary" onclick='copyToClipboard(`<%= form_html(@form) %>`)'>Copy to Clipboard</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
<!-- end::Embed Modal -->
<% content_for :page_scripts do %>
<%= javascript_include_tag 'copy-to-clipboard', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'custom_forms/new-form-field.js', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/custom_forms/show_tabs/_overview.html.erb
<!--begin::Row-->
<div class="row gx-6 gx-xl-9">
    <!--begin::Col-->
    <div class="col-lg-6">
        <!--begin::Summary-->
        <div class="card card-flush h-lg-100">
            <!--begin::Card header-->
            <div class="card-header mt-6">
                <!--begin::Card title-->
                <div class="card-title flex-column">
                    <h3 class="fw-bold mb-1">Submissions Summary</h3>
                    <div class="fs-6 fw-semibold text-gray-500">24 Overdue Tasks</div>
                </div>
                <!--end::Card title-->
                <!--begin::Card toolbar-->
                <div class="card-toolbar">
                    <a href="#" class="btn btn-light btn-sm">View Submissions</a>
                </div>
                <!--end::Card toolbar-->
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body p-9 pt-5">
                <!--begin::Wrapper-->
                <div class="d-flex flex-wrap">
                    <!--begin::Chart-->
                    <div class="position-relative d-flex flex-center h-175px w-175px me-15 mb-7">
                        <div class="position-absolute translate-middle start-50 top-50 d-flex flex-column flex-center">
                            <span class="fs-2qx fw-bold"><%= @form.form_submissions.count %></span>
                            <span class="fs-6 fw-semibold text-gray-500">Total Submissions</span>
                        </div>
                        <canvas id="project_overview_chart"></canvas>
                    </div>
                    <!--end::Chart-->
                    <!--begin::Labels-->
                    <div class="d-flex flex-column justify-content-center flex-row-fluid pe-11 mb-5">
                        <!--begin::Label-->
                        <div class="d-flex fs-6 fw-semibold align-items-center mb-3">
                            <div class="bullet bg-primary me-3"></div>
                            <div class="text-gray-500">In the last day</div>
                            <div class="ms-auto fw-bold text-gray-700"><%= @form.form_submissions.where("created_at >= ?", 24.hours.ago).count %></div>
                        </div>
                        <!--end::Label-->
                        <!--begin::Label-->
                        <div class="d-flex fs-6 fw-semibold align-items-center mb-3">
                            <div class="bullet bg-success me-3"></div>
                            <div class="text-gray-500">In the last week</div>
                            <div class="ms-auto fw-bold text-gray-700"><%= @form.form_submissions.where("created_at >= ?", 1.week.ago).count %></div>
                        </div>
                        <!--end::Label-->
                        <!--begin::Label-->
                        <div class="d-flex fs-6 fw-semibold align-items-center mb-3">
                            <div class="bullet bg-danger me-3"></div>
                            <div class="text-gray-500">In the last month</div>
                            <div class="ms-auto fw-bold text-gray-700"><%= @form.form_submissions.where("created_at >= ?", 30.days.ago).count %></div>
                        </div>
                        <!--end::Label-->
                        <!--begin::Label-->
                        <div class="d-flex fs-6 fw-semibold align-items-center">
                            <div class="bullet bg-gray-300 me-3"></div>
                            <div class="text-gray-500">In the last year</div>
                            <div class="ms-auto fw-bold text-gray-700"><%= @form.form_submissions.where("created_at >= ?", 1.year.ago).count %></div>
                        </div>
                        <!--end::Label-->
                    </div>
                    <!--end::Labels-->
                </div>
                <!--end::Wrapper-->
                <!--begin::Notice-->
                <div class="notice d-flex bg-light-primary rounded border-primary border border-dashed p-6">
                    <!--begin::Wrapper-->
                    <div class="d-flex flex-stack flex-grow-1">
                        <!--begin::Content-->
                        <div class="fw-semibold">
                            <div class="fs-6 text-gray-700">
                            <a href="#" class="fw-bold me-1">Invite New .NET Collaborators</a>to create great outstanding business to business .jsp modutr class scripts</div>
                        </div>
                        <!--end::Content-->
                    </div>
                    <!--end::Wrapper-->
                </div>
                <!--end::Notice-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Summary-->
    </div>
    <!--end::Col-->
    <!--begin::Col-->
    <div class="col-lg-6">
        <!--begin::Graph-->
        <div class="card card-flush h-lg-100">
            <!--begin::Card header-->
            <div class="card-header mt-6">
                <!--begin::Card title-->
                <div class="card-title flex-column">
                    <h3 class="fw-bold mb-1">Tasks Over Time</h3>
                    <!--begin::Labels-->
                    <div class="fs-6 d-flex text-gray-500 fs-6 fw-semibold">
                        <!--begin::Label-->
                        <div class="d-flex align-items-center me-6">
                        <span class="menu-bullet d-flex align-items-center me-2">
                            <span class="bullet bg-success"></span>
                        </span>Complete</div>
                        <!--end::Label-->
                        <!--begin::Label-->
                        <div class="d-flex align-items-center">
                        <span class="menu-bullet d-flex align-items-center me-2">
                            <span class="bullet bg-primary"></span>
                        </span>Incomplete</div>
                        <!--end::Label-->
                    </div>
                    <!--end::Labels-->
                </div>
                <!--end::Card title-->
                <!--begin::Card toolbar-->
                <div class="card-toolbar">
                    <!--begin::Select-->
                    <select name="status" data-control="select2" data-hide-search="true" class="form-select form-select-solid form-select-sm fw-bold w-100px">
                        <option value="1">2020 Q1</option>
                        <option value="2">2020 Q2</option>
                        <option value="3" selected="selected">2020 Q3</option>
                        <option value="4">2020 Q4</option>
                    </select>
                    <!--end::Select-->
                </div>
                <!--end::Card toolbar-->
            </div>
            <!--end::Card header-->
            <!--begin::Card body-->
            <div class="card-body pt-10 pb-0 px-5">
                <!--begin::Chart-->
                <div id="kt_project_overview_graph" class="card-rounded-bottom" style="height: 300px"></div>
                <!--end::Chart-->
            </div>
            <!--end::Card body-->
        </div>
        <!--end::Graph-->
    </div>
    <!--end::Col-->
</div>
<!--end::Row-->

<!--begin::SUBMISSIONS -->
<div class="card card-flush mt-6 mt-xl-9">
    <!--begin::Card header-->
    <div class="card-header mt-5">
        <!--begin::Card title-->
        <div class="card-title flex-column">
            <h3 class="fw-bold mb-1">Form Submissions</h3>
        </div>
        <!--begin::Card title-->
        <!--begin::Card toolbar-->
        <div class="card-toolbar my-1">
            <!--begin::Select-->
            <div class="me-6 my-1">
                <select id="kt_filter_year" name="year" data-control="select2" data-hide-search="true" class="w-125px form-select form-select-solid form-select-sm">
                    <option value="All" selected="selected">All time</option>
                    <option value="thisyear">This year</option>
                    <option value="thismonth">This month</option>
                    <option value="lastmonth">Last month</option>
                    <option value="last90days">Last 90 days</option>
                </select>
            </div>
            <!--end::Select-->
            <!--begin::Select-->
            <div class="me-4 my-1">
                <select id="kt_filter_orders" name="orders" data-control="select2" data-hide-search="true" class="w-125px form-select form-select-solid form-select-sm">
                    <option value="All" selected="selected">All Orders</option>
                    <option value="Approved">Approved</option>
                    <option value="Declined">Declined</option>
                    <option value="In Progress">In Progress</option>
                    <option value="In Transit">In Transit</option>
                </select>
            </div>
            <!--end::Select-->
            <!--begin::Search-->
            <div class="d-flex align-items-center position-relative my-1">
                <i class="ki-duotone ki-magnifier fs-3 position-absolute ms-3">
                    <span class="path1"></span>
                    <span class="path2"></span>
                </i>
                <input type="text" id="kt_filter_search" class="form-control form-control-solid form-select-sm w-150px ps-9" placeholder="Search Order" />
            </div>
            <!--end::Search-->
        </div>
        <!--begin::Card toolbar-->
    </div>
    <!--end::Card header-->
    <!--begin::Card body-->
    <div class="card-body pt-0">
        <!--begin::Table container-->
        <div class="table-responsive">
            <!--begin::Table-->
            <table id="kt_profile_overview_table" class="table table-row-bordered table-row-dashed gy-4 align-middle fw-bold">
                <thead class="fs-7 text-gray-500 text-uppercase">
                    <tr>
                        <th class="min-w-250px">Name</th>
                        <th class="min-w-90px text-end">Submissions</th>
                        <th class="min-w-90px text-end">Status</th>
                        <th class="min-w-100px text-end">Last Updated</th>
                        <th class="min-w-50px">Details</th>
                    </tr>
                </thead>
                <tbody class="fs-6">
                    <% @form.form_submissions.each do |submission| %>
                    <tr>
                        <td>
                            <!--begin::User-->
                            <div class="d-flex align-items-center">
                                <!--begin::Wrapper-->
                                <div class="me-5 position-relative">
                                    <!--begin::Avatar-->
                                    <div class="symbol symbol-35px symbol-circle">
                                        <img alt="Pic" src="assets/media/avatars/300-6.jpg" />
                                    </div>
                                    <!--end::Avatar-->
                                </div>
                                <!--end::Wrapper-->
                                <!--begin::Info-->
                                <div class="d-flex flex-column justify-content-center">
                                    <a href="<%= show_form_submission_path(params[:project_apikey], @form.apikey, submission.apikey) %>" class="fs-6 text-gray-800 text-hover-primary"><%= submission.name %></a>
                                    <div class="fw-semibold text-gray-500">smith@kpmg.com</div>
                                </div>
                                <!--end::Info-->
                            </div>
                            <!--end::User-->
                        </td>
                        <td class="text-end">1</td>
                        <td class="text-end">
                            <span class="badge badge-light-info fw-bold px-4 py-3">Active</span>
                        </td>
                        <td class="text-end"><%= submission.created_at.strftime("%b %d, %Y") %></td>
                        <td>
                            <a href="<%= show_form_submission_path(params[:project_apikey], @form.apikey, submission.apikey) %>" class="btn btn-light btn-sm">View</a>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <!--end::Table-->
        </div>
        <!--end::Table container-->
    </div>
    <!--end::Card body-->
</div>
<!--end::SUBMISSIONS -->