config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "accounts#show"

  #
  # WELCOME 
  #
  get '/sign-in', to: "welcome#signin", as: :signin
  post '/sign-in', to: "welcome#signin_do", as: :do_signin
  get '/sign-up', to: "welcome#signup", as: :signup
  post '/sign-up', to: "welcome#signup_do", as: :do_signup
  get '/signout', to: "welcome#signout", as: :signout

  #
  # ACCOUNTS 
  #
  get '/accounts', to: "accounts#select_accounts", as: :select_accounts
  get '/accounts/create/step-1', to: "accounts#create_account_1", as: :create_account_1
  post '/accounts/create/step-1', to: "accounts#create_account_1_do", as: :do_create_account_1
  get '/accounts/create/step-2', to: "accounts#create_account_2", as: :create_account_2
  post '/accounts/create/step-2', to: "accounts#create_account_2_do", as: :do_create_account_2
  get '/accounts/:id/select-plan', to: "accounts#select_plan", as: :select_plan
  get '/accounts/:account_token/select-plan/:plan_apikey', to: "accounts#select_plan_do", as: :do_select_plan
  get '/accounts/:id', to: "accounts#select_accounts_do", as: :do_select_accounts
  
  #
  # USERS
  #
  get '/users/invites/:invite_apikey/accept', to: 'users#accept_invite', as: :accept_invite
  get '/users/invites/:invite_apikey/decline', to: 'users#decline_invite', as: :decline_invite
  get '/users/invites', to: 'users#invites', as: :invites
  get '/users/invites/remove/:invite_apikey', to: 'users#remove_invite', as: :remove_invite
  get '/users/invites/resend/:invite_apikey', to: 'users#resend_invite', as: :resend_invite
  get '/users/new', to: 'users#new', as: :new_user
  post '/users/new', to: 'users#new_do', as: :do_new_user
  get '/users/:user_apikey/edit', to: 'users#edit', as: :edit_user
  get '/users', to: 'users#index', as: :users
  get '/users/:user_apikey', to: 'users#show', as: :show_user

  #
  # PROJECTS 
  #
  get '/projects', to: "projects#index", as: :projects
  get '/projects/new', to: "projects#new", as: :new_project
  post '/projects/create', to: "projects#create", as: :do_create_project
  get '/projects/:project_apikey', to: "projects#show", as: :show_project

  #
  # FORMS
  #
  get '/projects/:project_apikey/new', to: "custom_forms#new", as: :new_form
  post '/projects/:project_apikey/new', to: "custom_forms#create", as: :create_form
  get '/projects/:project_apikey/:form_apikey', to: "custom_forms#show", as: :show_form
  
  # FORM FIELDS
  get '/projects/:project_apikey/:form_apikey/new-form-field', to: "custom_forms#new_form_field", as: :new_form_field
  post '/projects/:project_apikey/:form_apikey/new-form-field', to: "custom_forms#create_form_field", as: :create_form_field
  get  '/projects/:project_apikey/:form_apikey/:form_field_apikey/edit', to: "custom_forms#edit_form_field", as: :edit_form_field
  post '/projects/:project_apikey/:form_apikey/:form_field_apikey/edit', to: "custom_forms#update_form_field", as: :update_form_field
  get  '/projects/:project_apikey/:form_apikey/:form_field_apikey/destroy', to: "custom_forms#destroy_form_field", as: :destroy_form_field

  # FORM SUBMISSIONS
  get '/projects/:project_apikey/:form_apikey/submission/:form_submission_apikey', to: "custom_forms#show_form_submission", as: :show_form_submission

  namespace :api do
    namespace :v1 do # Optional: API versioning
      get '/hello-world', to: 'custom_forms#hello_world'
      post '/form-submission/:form_apikey', to: 'custom_forms#form_submission'
    end
  end
end

app/views/layouts/components/_breadcrumb.html.erb
<ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
    <% breadcrumbs.each do |crumb| %>
        <li class="breadcrumb-item text-muted">
            <% if crumb.link? %>            
                <%= link_to crumb.name, crumb.path, class: "text-muted text-hover-primary" %>
            <% else %>   
                <%= crumb.name %>               
            <% end %>    
        </li>         
        <% unless crumb == breadcrumbs.last %>
            <li class="breadcrumb-item text-muted">
                <span class="bullet bg-gray-500 w-5px h-2px"></span>
            </li>
        <% end %>    
    <% end %>        
</ul>

app/views/layouts/components/_invites_notice.html.erb
<% if !@invites.empty? %>
    <div class="alert alert-info my-4">
    <p>You have one or more invites:</p>
    <% @invites.each do |invite| %>
        <div class="card card-task">
        <div class="card-body d-flex justify-content-between align-items-center">
            <div class="card-title mb-0">
            <a href="#"><h6><%= invite.account.name %></h6></a>
            <span class="text-small"><%= invite.from_user.name %></span>
            </div>
            <div class="card-meta">
            <a href="<%= decline_invite_path(invite.apikey) %>" class="btn btn-outline-secondary mr-2">Decline</a>
            <a href="<%= accept_invite_path(invite.apikey) %>" class="btn btn-primary">Accept</a>
            </div>
        </div>
        </div><!--end of task-->
    <% end %>
    </div>
<% end %>

app/views/layouts/components/_user_avatar.html.erb
<div class="avatar <%= "avatar-#{size}" if defined?(size) %>"><%= user_avatar %></div>